{{- if .Values.agent.install }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.jaeger.serviceName }}-agent
  labels:
    name: {{ .Values.jaeger.serviceName }}-agent
    app.kubernetes.io/name: {{ .Values.jaeger.serviceName }}-agent
    app.kubernetes.io/instance: {{ cat .Values.jaeger.serviceName "-agent-" .Release.Namespace | nospace | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/component: agent
    {{- include "jaeger.commonLabels" . | nindent 4 }}
    {{- if .Values.agent.labels }}
      {{- toYaml .Values.agent.labels | nindent 4 }}
    {{- end }}
{{- end }}
