collector.resources.requests.cpu: 200m
collector.resources.requests.memory: 64Mi
collector.resources.limits.cpu: 500m
collector.resources.limits.memory: 512Mi

query.resources.requests.cpu: 200m
query.resources.requests.memory: 128Mi
query.resources.limits.cpu: 500m
query.resources.limits.memory: 512Mi

proxy.resources.requests.cpu: 50m
proxy.resources.requests.memory: 100Mi
proxy.resources.limits.cpu: 100m
proxy.resources.limits.memory: 200Mi

readinessProbe.resources.requests.cpu: 10m
readinessProbe.resources.requests.memory: 32Mi
readinessProbe.resources.limits.cpu: 50m
readinessProbe.resources.limits.memory: 64Mi

integrationTests.resources.requests.cpu: 50m
integrationTests.resources.requests.memory: 256Mi
integrationTests.resources.limits.cpu: 400m
integrationTests.resources.limits.memory: 256Mi

statusProvisioner.resources.requests.cpu: 50m
statusProvisioner.resources.requests.memory: 50Mi
statusProvisioner.resources.limits.cpu: 100m
statusProvisioner.resources.limits.memory: 100Mi
