# Default values for jaeger.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
jaeger:
  storage:
    type: elasticsearch

# cassandraSchemaJob is ignored if jaeger.storage.type is set to elasticsearch.
elasticsearch:
  client:
    username: admin
    password: admin
    scheme: https
    url: vpc-test-es-1-3v65i7xkrsq7ucdl25mym4u5om.us-east-1.es.amazonaws.com
  indexCleaner:
    install: true
  lookback:
    install: true
  rollover:
    install: true

collector:
  install: true

query:
  install: true
  ingress:
    install: true
    host: query.<cloud_dns_name>

# This section is optional and allow to deploy a test service to generate some traces
# Useful if you want to verify how Jaeger receive, store and show traces
hotrod:
  install: true
  ingress:
    install: true
    host: hotrod.<cloud_dns_name>
