# Default values for jaeger.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
jaeger:
  storage:
    type: "elasticsearch"

# cassandraSchemaJob is ignored if jaeger.storage.type is set to elasticsearch.
elasticsearch:
  client:
    username: admin
    password: admin
    scheme: https
    url: elasticsearch.elasticsearch.svc:9200
  rollover:
    install: true
    initHook:
      ttlSecondsAfterFinished: 120
    schedule: "10 0 * * *"
    successfulJobsHistoryLimit: 1
    failedJobsHistoryLimit: 1
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 256m
        memory: 128Mi
  lookback:
    install: true
    schedule: "5 0 * * *"
    successfulJobsHistoryLimit: 1
    failedJobsHistoryLimit: 1
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 256m
        memory: 128Mi

collector:
  install: true

query:
  install: true
  route:
    install: true
    host: query.<cloud_dns_name>

# This section is optional and allow to deploy a test service to generate some traces
# Useful if you want to verify how Jaeger receive, store and show traces
hotrod:
  install: true
  ingress:
    install: true
    host: hotrod.<cloud_dns_name>
